### ISSUE TITLE
qiuck questions

### ISSUE THREAD

**Issue by Bruce9096** [chunyeow/LoRaMac-node#1]
Dear Chunyeow

I am a student doing the final project in UCL, my project is the sensor network based on sk-im880A, (generally connect temp sensor to im880, and then send the data to ic880)
I have a few questions: 
1.is the IDE you use KEil? 
2.and I am also confusing about the relationship about loramac, loramote.
3.since the loramote, sensor node, im880a are always is the same folder, could you please explain the relationship among them.
4.what is coproj file?
I am so sorry is these questions are a bit stupid, causeI just start with the MCU, and could you please give me some idea about this sensor project. thank you very much.^^

best wishes

Linyu

**Comment by chunyeow** [comment]
1. Free and open IDE: http://www.coocox.org/
2. LoRaMAC is the MAC protocol resided in the gateway. LoRaMote is for the sensors.
3. Which one you refer to?
4. CooCox project file.

**Comment by Bruce9096** [comment]
Hi Chun

very appreciate for your kindness help, I am now more familiar with IDE and
the code, now i am confusing about a new question,

I use the 880a as the node, 880c as the concentrator, now trying to read
the value of the GPIO pin, for example, GpioRead(PA_14), and Keil warning
that" incompatible integer to pointer conversion passing 'int' to parameter
of type of 'Gpio_t'

Could you please tell me how to figure this out? do I need to define the
pin as Gpio_t format? could you please give the detail to make the read
successfully,

thank you so much.

best wishes

2016-05-01 17:36 GMT+01:00 Chun-Yeow notifications@github.com:

**Comment by chunyeow** [comment]
Please check whether PA_14 is a GPIO pin.
